In [1]:
import cv2
import numpy as np
from imutils import face_utils
import imutils
import dlib

In [10]:
image = cv2.imread('/home/siddharth/Pictures/Webcam/face.jpg')
image = imutils.resize(image, width=500)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

overlay=image.copy()
output=image.copy()
p="shape_predictor_68_face_landmarks.dat"

detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(p)

rects = detector(gray, 1)
points=[]
 
for d in rects:
    cv2.rectangle(image, (d.left(), d.top()), (d.right(), d.bottom()), 255, 1)
    shape = predictor(image, d)
    shape = face_utils.shape_to_np(shape)
    #points =shape[27:36]
    (x, y, w, h) = cv2.boundingRect(np.array([shape[27:36]]))
    roi = image[y:y + h, x:x + w]
    
    #hull = cv2.convexHull(points)
    #image = cv2.drawContours(image, [hull], -1,(0, 255, 0) , -1)
    #cv2.circle(image, (p.x, p.y), 2, 255, 1)
    #cv2.putText(image, str(i), (p.x + 4, p.y), cv2.FONT_HERSHEY_SIMPLEX, 0.25, (255, 255, 255))
    
cv2.imshow("ROI", roi)
cv2.imshow("window", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

    
#shape = predictor(gray, rects) 
#shape = face_utils.shape_to_np(shape)
    

#nose=(27,35)

#required_pts=shape[27:35]

#hull = cv2.convexHull(required_pts)
#cv2.drawContours(overlay, [hull], -1,(0, 255, 0) , -1)
#cv2.addWeighted(overlay, alpha, output, 1 - alpha, 0, output)



In [11]:
Ycr=cv2.cvtColor(roi,cv2.COLOR_BGR2YCrCb)
ymean=np.mean(Ycr,axis = 0)
print(ymean)

[[ 76.66176471 126.14705882 129.52941176]
 [ 75.83823529 126.36764706 129.35294118]
 [ 73.55882353 126.80882353 129.25      ]
 [ 72.61764706 127.05882353 128.80882353]
 [ 71.55882353 127.44117647 128.38235294]
 [ 70.52941176 127.69117647 128.16176471]
 [ 70.39705882 127.91176471 127.47058824]
 [ 72.85294118 128.45588235 127.32352941]
 [ 76.13235294 128.58823529 126.94117647]
 [ 80.13235294 128.82352941 126.61764706]
 [ 86.79411765 129.19117647 126.45588235]
 [ 91.79411765 129.05882353 126.05882353]
 [ 96.14705882 128.91176471 125.98529412]
 [100.79411765 129.04411765 126.05882353]
 [108.52941176 128.94117647 125.89705882]
 [112.94117647 129.19117647 126.10294118]
 [117.23529412 129.35294118 126.07352941]
 [121.69117647 129.51470588 126.        ]
 [125.79411765 129.98529412 126.30882353]
 [127.47058824 130.14705882 126.39705882]
 [127.83823529 130.35294118 126.48529412]
 [127.45588235 130.54411765 126.67647059]
 [126.95588235 130.61764706 126.80882353]
 [124.85294118 130.64705882 126.88

In [48]:
min_YCrCb = np.array([60,120,110],np.uint8)
max_YCrCb = np.array([220,170,170],np.uint8)

image = cv2.imread("/home/siddharth/Pictures/Webcam/face.jpg")
imageYCrCb = cv2.cvtColor(image,cv2.COLOR_BGR2YCR_CB)
skinRegionYCrCb = cv2.inRange(imageYCrCb,min_YCrCb,max_YCrCb)

skinYCrCb = cv2.bitwise_and(image, image, mask = skinRegionYCrCb)
cv2.imshow('Seg',skinYCrCb) 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [49]:
cap=cv2.VideoCapture(0)
while True:
    ret,img=cap.read()
    imageYCrCb = cv2.cvtColor(img,cv2.COLOR_BGR2YCR_CB)
    skinRegionYCrCb = cv2.inRange(imageYCrCb,min_YCrCb,max_YCrCb)

    skinYCrCb = cv2.bitwise_and(img, img, mask = skinRegionYCrCb)
    cv2.imshow('img',skinYCrCb)
    if cv2.waitKey(1) == 13:
        break
cap.release()
cv2.destroyAllWindows()